# Generated by Django 3.2.8 on 2021-11-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Юзернейм')),
                ('phone_number', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Телефон')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Русский')], default=None, max_length=2, null=True, verbose_name='Язык')),
                ('date_joined', models.DateField(auto_now_add=True, null=True, verbose_name='Дата присоединения')),
            ],
            options={
                'verbose_name': '   пользователя',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
